version: '3'

services:
  mw-spa:
    image: mw-spa
    command: ["npm", "start"]
    env_file:
      - .env.docker
    environment:
      - NODE_ENV=production
    ports:
      - 8080:8080
    links:
      - mongodb

  mongodb:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
